<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageVersion Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.9.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.9.3" />
  </ItemGroup>
</Project>
